### PR TITLE
attempt to correct #23

### PR DESCRIPTION
**Pull request by msaunier-poctu**
* added configuration boolean field propagateTuples
* added constructor in CassandraCqlStateUpdater with a boolean to set propagateTuples value
* changed updateState method to propagate tuples if propagateTuples=true
* added TestCase

### CODE REVIEW

**Comment by lbruand-poctu** [comment]
:+1:

**Comment by ylorenza-poctu** [comment]
:+1:

**Comment by boneill42** [comment]
Love it.

**Comment by lbruand-poctu** [comment]
Thanks!

**Pull request merged**
